owner: context-layer
repo: cl-status

sites:
  - name: CL Core API
    url: https://api.cl.kaisek.com/api/health

  - name: CL Console
    url: https://cl.kaisek.com

  - name: CL Backend
    url: https://cl.kaisek.com/api/health

assignees:
  - context-layer

status-website:
  cname: status.cl.kaisek.com
  name: Context Layer Status
